skip_branch_with_pr: true

image: Visual Studio 2019
configuration: Release

before_build:
  - ps: gitversion /l console /output buildserver

build_script:
  - ps: dotnet restore src\SpeakEasy.sln
  - ps: dotnet build src\SpeakEasy.sln --no-restore --configuration Release /p:Version=%GitVersion_SemVer% /p:AssemblyVersion=%GitVersion_AssemblySemVer% /p:FileVersion=%GitVersion_AssemblySemFileVer% /p:InformationalVersion=%GitVersion_InformationalVersion%
  - ps: dotnet pack src\SpeakEasy.sln --configuration Release --no-restore --no-build --output artifacts /p:Version=%GitVersion_SemVer%

test_script:
  - ps: dotnet test src\SpeakEasy.sln

artifacts:
  - path: artifacts/*

deploy:
  provider: NuGet
  skip_symbols: true
  api_key:
    secure: oG6FNO1zPKE7PDFAlOw9AmsVV2ZxO3VIWorkUXD4oKALfTd+p8E1IYIf22ZyS3LU
  on:
    appveyor_repo_tag: true
  artifact: /.*\.nupkg/
