skip_branch_with_pr: true

# build cache to preserve files/folders between builds
cache:
  - '%LocalAppData%\NuGet\v3-cache'

image: Visual Studio 2017
configuration: Release

install:
  - choco install gitversion.portable -pre -y
  - cmd: dotnet restore src\SpeakEasy.sln
  - ps: gitversion /l console /output buildserver

dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: $(GitVersion_NuGetVersion)
  package_version: $(GitVersion_NuGetVersion)
  assembly_version: $(GitVersion_MajorMinorPatch)
  file_version: $(GitVersion_MajorMinorPatch)
  informational_version: $(GitVersion_MajorMinorPatch)

build:
  parallel: true
  project: src\SpeakEasy.sln
  publish_nuget: true
  publish_nuget_symbols: true

test_script:
  - ps: .\build\run-tests.ps1

deploy:
  provider: NuGet
  skip_symbols: true
  api_key:
    secure: oG6FNO1zPKE7PDFAlOw9AmsVV2ZxO3VIWorkUXD4oKALfTd+p8E1IYIf22ZyS3LU
  on:
    appveyor_repo_tag: true
